
package com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RxActiveReminderDeterminationDecisionService", targetNamespace = "http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination.ObjectFactory.class,
    com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination.param.ObjectFactory.class
})
public interface RxActiveReminderDeterminationDecisionService {


    /**
     * 
     * @param rxActiveReminderDeterminationRequest
     * @return
     *     returns com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination.RxActiveReminderDeterminationResponse
     * @throws RxActiveReminderDeterminationSoapFault
     */
    @WebMethod(operationName = "RxActiveReminderDetermination", action = "RxActiveReminderDetermination")
    @WebResult(name = "RxActiveReminderDeterminationResponse", targetNamespace = "http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination", partName = "RxActiveReminderDeterminationResponse")
    public RxActiveReminderDeterminationResponse rxActiveReminderDetermination(
        @WebParam(name = "RxActiveReminderDeterminationRequest", targetNamespace = "http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination", partName = "RxActiveReminderDeterminationRequest")
        RxActiveReminderDeterminationRequest rxActiveReminderDeterminationRequest)
        throws RxActiveReminderDeterminationSoapFault
    ;

}
