
package com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "RxActiveReminderDeterminationException", targetNamespace = "http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination")
public class RxActiveReminderDeterminationSoapFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private RxActiveReminderDeterminationException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public RxActiveReminderDeterminationSoapFault(String message, RxActiveReminderDeterminationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public RxActiveReminderDeterminationSoapFault(String message, RxActiveReminderDeterminationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination.RxActiveReminderDeterminationException
     */
    public RxActiveReminderDeterminationException getFaultInfo() {
        return faultInfo;
    }

}
