
package com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/*import ca.sdm.cdr.common.constant.Constants;
import ca.sdm.cdr.common.singleton.CDRConfigFileReader;
import ca.sdm.cdr.common.singleton.TableColumnSingleton;*/


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 *
 @WebServiceClient(name = "RxActiveReminderDeterminationDecisionService", targetNamespace = "http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination", wsdlLocation = "http://localhost:9095/DecisionService/ws/DigitalRxRuleService/RxActiveReminderDetermination?WSDL")
 */
public class RxActiveReminderDeterminationDecisionService_Service
    extends Service
{

    private final static URL RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_EXCEPTION;
    private final static QName RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_QNAME = new QName("http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination", "RxActiveReminderDeterminationDecisionService");

    static {
        WebServiceException e = null;
        URL url = null;
        

/*        
        try {
            url = new URL("http://10.108.76.44:9095/DecisionService/ws/DigitalRxRuleService/RxActiveReminderDetermination?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
*/
        
        try {
      	     URL baseUrl;
             baseUrl = com.ibm.rules.decisionservice.digitalrxruleservice.rxactivereminderdetermination.RxActiveReminderDeterminationDecisionService_Service.class.getResource(".");
            
            url = new URL(baseUrl, "http://localhost/wsdl/RxActiveReminderDetermination.wsdl");//WEB-INF/wsdl
          //   url = new URL(baseUrl, "WEB-INF/wsdl/localhost_8080/MedicationProfileService/RxActiveReminderDetermination.wsdl");
        } catch (MalformedURLException ex) {
             e = new WebServiceException(ex);
        }        
        RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_WSDL_LOCATION = url;
        RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_EXCEPTION = e;
    }

    public RxActiveReminderDeterminationDecisionService_Service() {
        super(__getWsdlLocation(), RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_QNAME);
    }

    public RxActiveReminderDeterminationDecisionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_QNAME, features);
    }

    public RxActiveReminderDeterminationDecisionService_Service(URL wsdlLocation) {
        super(wsdlLocation, RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_QNAME);
    }

    public RxActiveReminderDeterminationDecisionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_QNAME, features);
    }

    public RxActiveReminderDeterminationDecisionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RxActiveReminderDeterminationDecisionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RxActiveReminderDeterminationDecisionService
     */
    @WebEndpoint(name = "DigitalRxRuleServiceRxActiveReminderDeterminationPort")
    public RxActiveReminderDeterminationDecisionService getDigitalRxRuleServiceRxActiveReminderDeterminationPort() {
        return super.getPort(new QName("http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination", "DigitalRxRuleServiceRxActiveReminderDeterminationPort"), RxActiveReminderDeterminationDecisionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RxActiveReminderDeterminationDecisionService
     */
    @WebEndpoint(name = "DigitalRxRuleServiceRxActiveReminderDeterminationPort")
    public RxActiveReminderDeterminationDecisionService getDigitalRxRuleServiceRxActiveReminderDeterminationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ibm.com/rules/decisionservice/DigitalRxRuleService/RxActiveReminderDetermination", "DigitalRxRuleServiceRxActiveReminderDeterminationPort"), RxActiveReminderDeterminationDecisionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_EXCEPTION!= null) {
            throw RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_EXCEPTION;
        }
        return RXACTIVEREMINDERDETERMINATIONDECISIONSERVICE_WSDL_LOCATION;
    }

}
