
package ca.shoppersdrugmart.rxhb.drx.patientservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PatientService", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/PatientService", wsdlLocation = "/wsdls/PatientService.wsdl")
public class PatientService_Service
    extends Service
{

    private final static URL PATIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PATIENTSERVICE_EXCEPTION;
    private final static QName PATIENTSERVICE_QNAME = new QName("http://shoppersdrugmart.ca/RxHB/DRx/PatientService", "PatientService");

    static {
        PATIENTSERVICE_WSDL_LOCATION = ca.shoppersdrugmart.rxhb.drx.patientservice.PatientService_Service.class.getResource("/wsdls/PatientService.wsdl");
        WebServiceException e = null;
        if (PATIENTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/PatientService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PATIENTSERVICE_EXCEPTION = e;
    }

    public PatientService_Service() {
        super(__getWsdlLocation(), PATIENTSERVICE_QNAME);
    }

    public PatientService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PATIENTSERVICE_QNAME, features);
    }

    public PatientService_Service(URL wsdlLocation) {
        super(wsdlLocation, PATIENTSERVICE_QNAME);
    }

    public PatientService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PATIENTSERVICE_QNAME, features);
    }

    public PatientService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PatientService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PatientService
     */
    @WebEndpoint(name = "PatientService")
    public PatientService getPatientService() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/PatientService", "PatientService"), PatientService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PatientService
     */
    @WebEndpoint(name = "PatientService")
    public PatientService getPatientService(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/PatientService", "PatientService"), PatientService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PATIENTSERVICE_EXCEPTION!= null) {
            throw PATIENTSERVICE_EXCEPTION;
        }
        return PATIENTSERVICE_WSDL_LOCATION;
    }

}
