
package ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2services;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2.SubscriptionEntityType;
import ca.shoppersdrugmart.rxhb.ehealth.PharmacyChannel;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "SubscriptoinServiceV2", serviceName = "SubscriptionServiceV2", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2Services", wsdlLocation = "/wsdls/SubscriptionServiceV2.wsdl", endpointInterface = "ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2services.SubscriptionServiceV2")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class SubscriptionServiceV2_SubscriptoinServiceV2Impl implements SubscriptionServiceV2 {

	public SubscriptionServiceV2_SubscriptoinServiceV2Impl() {
	}

	/**
	 * 
	 * @param storeNumber
	 * @param entityType
	 * @param sourceChannel
	 * @param entityId
	 * @return returns java.lang.String
	 */
	public String subscribeToEntityBySourceChannel(String storeNumber, SubscriptionEntityType entityType,
			String entityId, PharmacyChannel sourceChannel) {
		// replace with your impl here
		return null;
	}

	/**
	 * 
	 * @param storeNumber
	 * @param entityType
	 * @param pharmacyChannel
	 * @param entityId
	 * @return returns java.lang.String
	 */
	public String unSubscribeToEntityBySourceChannel(String storeNumber, SubscriptionEntityType entityType,
			String entityId, PharmacyChannel pharmacyChannel) {
		// replace with your impl here
		return null;
	}

}
