
package ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2services;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriptionServiceV2", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2Services", wsdlLocation = "/wsdls/SubscriptionServiceV2.wsdl")
public class SubscriptionServiceV2_Service
    extends Service
{

    private final static URL SUBSCRIPTIONSERVICEV2_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIPTIONSERVICEV2_EXCEPTION;
    private final static QName SUBSCRIPTIONSERVICEV2_QNAME = new QName("http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2Services", "SubscriptionServiceV2");

    static {
        SUBSCRIPTIONSERVICEV2_WSDL_LOCATION = ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2services.SubscriptionServiceV2_Service.class.getResource("/wsdls/SubscriptionServiceV2.wsdl");
        WebServiceException e = null;
        if (SUBSCRIPTIONSERVICEV2_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/SubscriptionServiceV2.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SUBSCRIPTIONSERVICEV2_EXCEPTION = e;
    }

    public SubscriptionServiceV2_Service() {
        super(__getWsdlLocation(), SUBSCRIPTIONSERVICEV2_QNAME);
    }

    public SubscriptionServiceV2_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIPTIONSERVICEV2_QNAME, features);
    }

    public SubscriptionServiceV2_Service(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIPTIONSERVICEV2_QNAME);
    }

    public SubscriptionServiceV2_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIPTIONSERVICEV2_QNAME, features);
    }

    public SubscriptionServiceV2_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionServiceV2_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriptionServiceV2
     */
    @WebEndpoint(name = "SubscriptoinServiceV2")
    public SubscriptionServiceV2 getSubscriptoinServiceV2() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2Services", "SubscriptoinServiceV2"), SubscriptionServiceV2.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionServiceV2
     */
    @WebEndpoint(name = "SubscriptoinServiceV2")
    public SubscriptionServiceV2 getSubscriptoinServiceV2(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2Services", "SubscriptoinServiceV2"), SubscriptionServiceV2.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIPTIONSERVICEV2_EXCEPTION!= null) {
            throw SUBSCRIPTIONSERVICEV2_EXCEPTION;
        }
        return SUBSCRIPTIONSERVICEV2_WSDL_LOCATION;
    }

}
