
package ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2.SubscriptionEntityType;
import ca.shoppersdrugmart.rxhb.ehealth.PharmacyChannel;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriptionServiceV2", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2Services")
@XmlSeeAlso({
    ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class
})
public interface SubscriptionServiceV2 {


    /**
     * 
     * @param storeNumber
     * @param entityType
     * @param sourceChannel
     * @param entityId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/SubscriptionServiceV2/subscribeToEntityBySourceChannel")
    @WebResult(name = "flag", targetNamespace = "")
    @RequestWrapper(localName = "subscribeToEntityBySourceChannel", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2", className = "ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2.SubscribeToEntityBySourceChannel")
    @ResponseWrapper(localName = "subscribeToEntityBySourceChannelResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2", className = "ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2.SubscribeToEntityBySourceChannelResponse")
    public String subscribeToEntityBySourceChannel(
        @WebParam(name = "storeNumber", targetNamespace = "")
        String storeNumber,
        @WebParam(name = "entityType", targetNamespace = "")
        SubscriptionEntityType entityType,
        @WebParam(name = "entityId", targetNamespace = "")
        String entityId,
        @WebParam(name = "sourceChannel", targetNamespace = "")
        PharmacyChannel sourceChannel);

    /**
     * 
     * @param storeNumber
     * @param entityType
     * @param pharmacyChannel
     * @param entityId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/SubscriptionServiceV2/unSubscribeToEntityBySourceChannel")
    @WebResult(name = "flag", targetNamespace = "")
    @RequestWrapper(localName = "unSubscribeToEntityBySourceChannel", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2", className = "ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2.UnSubscribeToEntityBySourceChannel")
    @ResponseWrapper(localName = "unSubscribeToEntityBySourceChannelResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceV2", className = "ca.shoppersdrugmart.rxhb.drx.subscriptionservicev2.UnSubscribeToEntityBySourceChannelResponse")
    public String unSubscribeToEntityBySourceChannel(
        @WebParam(name = "storeNumber", targetNamespace = "")
        String storeNumber,
        @WebParam(name = "entityType", targetNamespace = "")
        SubscriptionEntityType entityType,
        @WebParam(name = "entityId", targetNamespace = "")
        String entityId,
        @WebParam(name = "PharmacyChannel", targetNamespace = "http://shoppersdrugmart.ca/RxHB/eHealth")
        PharmacyChannel pharmacyChannel);

}
