
package ca.shoppersdrugmart.cdr.purgingservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PurgingService", targetNamespace = "http://shoppersdrugmart.ca/cdr/PurgingService", wsdlLocation = "/wsdls/PurgingService.wsdl")
public class PurgingService_Service
    extends Service
{

    private final static URL PURGINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PURGINGSERVICE_EXCEPTION;
    private final static QName PURGINGSERVICE_QNAME = new QName("http://shoppersdrugmart.ca/cdr/PurgingService", "PurgingService");
    static {
    	PURGINGSERVICE_WSDL_LOCATION = ca.shoppersdrugmart.cdr.purgingservice.PurgingService_Service.class.getResource("/wsdls/PatientService.wsdl");
        WebServiceException e = null;
        if (PURGINGSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/PatientService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PURGINGSERVICE_EXCEPTION = e;
    }
  /*  static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/DROP%2040/updated%20wsdl/PurgingService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PURGINGSERVICE_WSDL_LOCATION = url;
        PURGINGSERVICE_EXCEPTION = e;
    }*/

    public PurgingService_Service() {
        super(__getWsdlLocation(), PURGINGSERVICE_QNAME);
    }

    public PurgingService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PURGINGSERVICE_QNAME, features);
    }

    public PurgingService_Service(URL wsdlLocation) {
        super(wsdlLocation, PURGINGSERVICE_QNAME);
    }

    public PurgingService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PURGINGSERVICE_QNAME, features);
    }

    public PurgingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PurgingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PurgingService
     */
    @WebEndpoint(name = "PurgingService")
    public PurgingService getPurgingService() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PurgingService", "PurgingService"), PurgingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PurgingService
     */
    @WebEndpoint(name = "PurgingService")
    public PurgingService getPurgingService(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PurgingService", "PurgingService"), PurgingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PURGINGSERVICE_EXCEPTION!= null) {
            throw PURGINGSERVICE_EXCEPTION;
        }
        return PURGINGSERVICE_WSDL_LOCATION;
    }

}
