
package ca.shoppersdrugmart.cdr.purgingservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PurgingService", targetNamespace = "http://shoppersdrugmart.ca/cdr/PurgingService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PurgingService {


    /**
     * 
     * @param purgingProcess
     * @return
     *     returns ca.shoppersdrugmart.cdr.purgingservice.PurgingProcessResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/cdr/PurgingService/purgingProcess")
    @WebResult(name = "PurgingProcessResponse", targetNamespace = "http://shoppersdrugmart.ca/cdr/PurgingService", partName = "PurgingProcessResponse")
    public PurgingProcessResponse purgingProcess(
        @WebParam(name = "PurgingProcess", targetNamespace = "http://shoppersdrugmart.ca/cdr/PurgingService", partName = "PurgingProcess")
        PurgingProcess purgingProcess);

}
