
node{
	
		stage('---CLEAN--'){
			
			git 'https://github.com/thogeti/SpringBoot.git'
		//	sh "mvn clean"
			
		}
		stage('---Packeage--'){
			
			def mvnHome=tool name: 'Maven', type: 'maven'
			sh '${mvnHome}/bin/mvn package'
			
		}
	
	
}
