
node{
	stages{
		stage('---CLEAN--'){
			steps{
			git 'https://github.com/thogeti/SpringBoot/tree/Develop'
		//	sh "mvn clean"
			}
		}
		stage('---Packeage--'){
			steps{
			def mvnHome=tool name: 'Maven', type: 'maven'
			sh '${mvnHome}/bin/mvn package'
			}
		}
	
	}
}
