
package com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
//@WebServiceClient(name = "MedcheckDeterminationDecisionService", targetNamespace = "http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination", wsdlLocation = "http://laheesbdv255.ngco.com:9095/DecisionService/ws/MedcheckRuleApp/MedcheckDetermination/v75?WSDL")
public class MedcheckDeterminationDecisionService_Service
    extends Service
{

    private final static URL MEDCHECKDETERMINATIONDECISIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDCHECKDETERMINATIONDECISIONSERVICE_EXCEPTION;
    private final static QName MEDCHECKDETERMINATIONDECISIONSERVICE_QNAME = new QName("http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination", "MedcheckDeterminationDecisionService");

    static {
         
        WebServiceException e = null;
        URL url = null;
        URL baseUrl;
       
       
       try {
    	   baseUrl = com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination.MedcheckDeterminationDecisionService_Service.class.getResource(".");
		   url = new URL(baseUrl, "http://localhost/wsdl/MedcheckDetermination.wsdl");
		    
	} catch (MalformedURLException e1) {
		// TODO Auto-generated catch block
		e1.printStackTrace();
	}//WEB-INF/wsdl
             MEDCHECKDETERMINATIONDECISIONSERVICE_WSDL_LOCATION =url;
		 if (MEDCHECKDETERMINATIONDECISIONSERVICE_WSDL_LOCATION == null) {
	            e = new WebServiceException("Cannot find '/wsdls/MedcheckDetermination.wsdl' wsdl. Place the resource correctly in the classpath.");
	        }
      
        MEDCHECKDETERMINATIONDECISIONSERVICE_EXCEPTION = e;
    }

    public MedcheckDeterminationDecisionService_Service() {
        super(__getWsdlLocation(), MEDCHECKDETERMINATIONDECISIONSERVICE_QNAME);
    }

    public MedcheckDeterminationDecisionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDCHECKDETERMINATIONDECISIONSERVICE_QNAME, features);
    }

    public MedcheckDeterminationDecisionService_Service(URL wsdlLocation) {
        super(wsdlLocation, MEDCHECKDETERMINATIONDECISIONSERVICE_QNAME);
    }

    public MedcheckDeterminationDecisionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDCHECKDETERMINATIONDECISIONSERVICE_QNAME, features);
    }

    public MedcheckDeterminationDecisionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedcheckDeterminationDecisionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MedcheckDeterminationDecisionService
     */
    @WebEndpoint(name = "MedcheckRuleAppMedcheckDeterminationPort")
    public MedcheckDeterminationDecisionService getMedcheckRuleAppMedcheckDeterminationPort() {
        return super.getPort(new QName("http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination", "MedcheckRuleAppMedcheckDeterminationPort"), MedcheckDeterminationDecisionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedcheckDeterminationDecisionService
     */
    @WebEndpoint(name = "MedcheckRuleAppMedcheckDeterminationPort")
    public MedcheckDeterminationDecisionService getMedcheckRuleAppMedcheckDeterminationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination", "MedcheckRuleAppMedcheckDeterminationPort"), MedcheckDeterminationDecisionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDCHECKDETERMINATIONDECISIONSERVICE_EXCEPTION!= null) {
            throw MEDCHECKDETERMINATIONDECISIONSERVICE_EXCEPTION;
        }
        return MEDCHECKDETERMINATIONDECISIONSERVICE_WSDL_LOCATION;
    }

}
