
package com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MedcheckDeterminationException", targetNamespace = "http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination")
public class MedcheckDeterminationSoapFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MedcheckDeterminationException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MedcheckDeterminationSoapFault(String message, MedcheckDeterminationException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MedcheckDeterminationSoapFault(String message, MedcheckDeterminationException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination.MedcheckDeterminationException
     */
    public MedcheckDeterminationException getFaultInfo() {
        return faultInfo;
    }

}
