
package com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MedcheckDeterminationDecisionService", targetNamespace = "http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination.ObjectFactory.class,
    com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination.param.ObjectFactory.class
})
public interface MedcheckDeterminationDecisionService {


    /**
     * 
     * @param medcheckDeterminationRequest
     * @return
     *     returns com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination.MedcheckDeterminationResponse
     * @throws MedcheckDeterminationSoapFault
     */
    @WebMethod(operationName = "MedcheckDetermination", action = "MedcheckDetermination")
    @WebResult(name = "MedcheckDeterminationResponse", targetNamespace = "http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination", partName = "MedcheckDeterminationResponse")
    public MedcheckDeterminationResponse medcheckDetermination(
        @WebParam(name = "MedcheckDeterminationRequest", targetNamespace = "http://www.ibm.com/rules/decisionservice/MedcheckRuleApp/MedcheckDetermination", partName = "MedcheckDeterminationRequest")
        MedcheckDeterminationRequest medcheckDeterminationRequest)
        throws MedcheckDeterminationSoapFault
    ;

}
