SELECT  
        --DRG.DRGID DRG_DRGID,
        --DRG.EQUVNLTTO DRG_EQUVNLTTO,
       -- DRG.ALTRNTVNM DRG_ALTRNTVNM,
        --DRG.TRDNMALTRNTV DRG_TRDNMALTRNTV,
       -- DRG.BRANDDRG DRG_BRANDDRG, 
       -- DRG.TRDREF DRG_TRDREF,
        DRG.DIN DRG_DIN,
      --  DRG.CNSMRID DRG_CNSMRID,
      --  DRG.MONOGRAPH DRG_MONOGRAPH,
      --  DRG.PRDCRID DRG_PRDCRID, 
      --  DRG.FRMVARIANT DRG_FRMVARIANT,
      --  DRG.ISDEVICE DRG_ISDEVICE, 
      --  DRG.ADLTDSGMAXQTY DRG_ADLTDSGMAXQTY,
      --  DRG.CHLDDSGMINQTY DRG_CHLDDSGMINQTY, 
      --  DRG.ADLTDSGMINQTY DRG_ADLTDSGMINQTY,
      --  DRG.CHLDDSGMAXQTY DRG_CHLDDSGMAXQTY,
        DRG.ISIMMNZTN DRG_ISIMMNZTN,--
      --  DRG.ISPROP DRG_ISPROP, 
      --  DRG.ISREPORTABLE DRG_ISREPORTABLE, 
      --  DRG.ISWRTN DRG_ISWRTN, DRG.MRKNG DRG_MRKNG, 
        DRG.CHMCLLBLNMENG DRG_CHMCLLBLNMENG,--
        DRG.CHMCLLBLNMFR DRG_CHMCLLBLNMFR,--
        DRG.TRDNMENG DRG_TRDNMENG,--
        DRG.TRDNMFR DRG_TRDNMFR,--
      --  DRG.DRGDESCR DRG_DRGDESCR,
      --  DRG.STORENUM DRG_STORENUM,
       -- DRG.ADMINRTETYPKEY DRG_ADMINRTETYPKEY,
     --   DRG.DINTYPKEY DRG_DINTYPKEY, 
     --   DRG.DRGFLVRTYPKEY DRG_DRGFLVRTYPKEY,
     --   DRG.DRGSCHDLTYPKEY DRG_DRGSCHDLTYPKEY,
    --    DRG.DRGSHPTYPKEY DRG_DRGSHPTYPKEY,
     --   DRG.SPCLDRGPROGTYPKEY DRG_SPCLDRGPROGTYPKEY, 
     --   DRG.SUBRSNTYPKEY DRG_SUBRSNTYPKEY, 
     --   DRG.MFCTRKEY DRG_MFCTRKEY,
     --   DRG.DSGFRMKEY DRG_DSGFRMKEY,
     --   DRG.DRGPRDGRPTYPKEY DRG_DRGPRDGRPTYPKEY, 
     --   DSGFRM.DSGFRMFULLNM DSGFRM_DSGFRMFULLNM,--
      --  DSGFRM.DSGFRMID DSGFRM_DSGFRMID,
   --     DSGFRM.DSGFRMSHORTNM DSGFRM_DSGFRMSHORTNM, 
        MFCTR.MFCTRNMENG MFCTR_MFCTRNMENG,
        MFCTR.MFCTRID MFCTR_MFCTRID,
        MFCTR.MFCTRPREFIX MFCTR_MFCTRPREFIX,
        MFCTR.VENDORCD MFCTR_VENDORCD, 
        MFCTR.MFCTRNMFR MFCTR_MFCTRNMFR,
        MLCL.MLCLKEY MLCL_MLCLKEY 
        FROM DRG
        LEFT OUTER JOIN DSGFRM DSGFRM ON DRG.DSGFRMKEY = DSGFRM.DSGFRMKEY 
     --   LEFT OUTER JOIN MFCTR MFCTR ON DRG.MFCTRKEY = MFCTR.MFCTRKEY
     --   LEFT OUTER JOIN MLCL MLCL ON DRG.MLCLKEY = MLCL.MLCLKEY
        WHERE DRG.DRGKEY = ?