--TE97_024
select tmp_ptnt.PTNTKEY            as Ptnt_PTNTKEY,
       tmp_ptnt.CNSMRID            as Ptnt_CNSMRID,
       
       ptntid.idnum                as ptntid_idnum,
       ptntid.ptntidkey            as ptntid_ptntidkey,
        ptntid.issngathrtynm          AS ptntid_issngathrtynm ,
        ptntid.idtypkey               AS ptntid_idtypkey ,
       tmp_ptnt.FRSTNM             as Ptnt_FRSTNM,
       tmp_ptnt.LSTNM              as Ptnt_LSTNM,
      -- tmp_ptnt.SALUTATION         as Ptnt_SALUTATION,  --TE99
       tmp_ptnt.MDLNM              as Ptnt_MDLNM,
       tmp_ptnt.CRTTIMESTAMP       as Ptnt_CRTTIMESTAMP,
       tmp_ptnt.LSTUPDTTIMESTAMP   as Ptnt_LSTUPDTTIMESTAMP,
       tmp_ptnt.DTOFBIRTH          as Ptnt_DTOFBIRTH,
       tmp_ptnt.DCSDDT             as Ptnt_DCSDDT,
       tmp_ptnt.GNDRTYPKEY         as Ptnt_GNDRTYPKEY,
       tmp_ptnt.NOKNWNALRGYFLG     as Ptnt_NOKNWNALRGYFLG,
       tmp_ptnt.PTNTACTIND         as Ptnt_PTNTACTIND,
       tmp_ptnt.PTNTTYPKEY         as Ptnt_PTNTTYPKEY,
       tmp_ptnt.MOBILENUM          as Ptnt_MOBILENUM,   --TE99--Drop56
       tmp_ptnt.GRPMBRSHPTYPKEY    as Ptnt_GRPMBRSHPTYPKEY,
       tmp_ptnt.PTNTOPTNOPTTYPKEY  as Ptnt_PTNTOPTNOPTTYPKEY,
       tmp_ptnt.LANGUAGECORRESPONDENCE   AS ptnt_LANGUAGECORRESPONDENCE, 
       tmp_ptnt.SIGLANGUAGE              AS ptnt_SIGLANGUAGE,
       tmp_ptnt.MONOGRAPHLANGUAGE        AS ptnt_MONOGRAPHLANGUAGE,
       CM_CNSMRID,
       cntctmthdtypcd,
       CNTCTPRPSTYPKEY,
       CNTCTPRPSTYPCD              as ADDR_TYPE,  --TE99
       EMAIL_EMAILADDR,                                     
       EMAIL_EMAILKEY,
       EMAIL_ROWID,
       PHONE_ROWID,
       PHONE_TELECOMKEY,
       PHONE_TELFAXIND,
       PHONE_CNTRYCD,
       PHONE_TELECOMNUM,
       ALTERN_TELECOMKEY,
       ALTERN_ROWID,
       ALTERN_TELFAXIND,
       ALTERN_CNTRYCD,
       ALTERN_TELECOMNUM,
       FAX_ROWID,
       FAX_TELECOMKEY,
       FAX_TELFAXIND,
       FAX_CNTRYCD,
       FAX_TELECOMNUM,
       addr_addrkey,
       addr_ADDRLNONE,
       addr_ADDRLNTWO,
       addr_CITYNM,
       addr_CNTRYCD,
       addr_POSTALCD,
       addr_PROVCD,
       ADDR_ROWID
             from   (select p.PTNTTYPKEY,
                            p.CRTTIMESTAMP,
                            p.CNSMRID,
                            p.DCSDDT,
                            p.DTOFBIRTH,
                            p.FRSTNM,
                            p.GNDRTYPKEY,
                            p.GRPMBRSHPTYPKEY,
                            p.LSTNM,
                            p.LSTUPDTTIMESTAMP,
                            p.MDLNM,
                            p.NOKNWNALRGYFLG,
                            p.PTNTACTIND,
                            p.PTNTKEY,
                            p.PTNTOPTNOPTTYPKEY,
                         --,
                         --   p.SALUTATION,        --TE99
                            p.MOBILENUM,          --TE99
                            p.LANGUAGECORRESPONDENCE,
                            p.SIGLANGUAGE,
                            p.MONOGRAPHLANGUAGE
                       from ptnt p
