SELECT DISTINCT ptnt.cnsmrid                  AS ptnt_cnsmrid ,
                ptnt.crttimestamp             AS ptnt_crttimestamp ,
                ptnt.dcsddt                   AS ptnt_dcsddt ,
                ptnt.dtofbirth                AS ptnt_dtofbirth ,
                ptnt.frstnm                   AS ptnt_frstnm ,
                ptnt.gndrtypkey               AS ptnt_gndrtypkey ,
                ptnt.grpmbrshptypkey          AS ptnt_grpmbrshptypkey ,
                ptnt.lstnm                    AS ptnt_lstnm ,
                ptnt.lstupdttimestamp         AS ptnt_lstupdttimestamp ,
                ptnt.mdlnm                    AS ptnt_mdlnm ,
                ptnt.noknwnalrgyflg           AS ptnt_noknwnalrgyflg ,
                ptnt.ptntactind               AS ptnt_ptntactind ,
                ptnt.ptntkey                  AS ptnt_ptntkey ,
                ptnt.ptntoptnopttypkey        AS ptnt_ptntoptnopttypkey ,
                ptnt.ptnttypkey               AS ptnt_ptnttypkey ,
                ptnt.rcrdrkey                 AS ptnt_rcrdrkey ,
                ptnt.sndxfrstnm               AS ptnt_sndxfrstnm ,
                ptnt.sndxlstnm                AS ptnt_sndxlstnm ,
                ptnt.storenum                 AS ptnt_storenum,
                ptnt.mobilenum			      AS ptnt_mobilenum,
                ptnt.languagecorrespondence   AS ptnt_languagecorrespondence, 
                ptnt.siglanguage              AS ptnt_siglanguage,
                ptnt.monographlanguage        AS ptnt_monographlanguage,
                
                
                p_c_vw.addr_addrkey           AS addr_addrkey ,
                p_c_vw.addr_addrlnone         AS addr_addrlnone ,
                p_c_vw.addr_addrlntwo         AS addr_addrlntwo ,
                p_c_vw.addr_citynm            AS addr_citynm ,
                p_c_vw.addr_cntrycd           AS addr_cntrycd ,
                p_c_vw.addr_postalcd          AS addr_postalcd ,
                p_c_vw.addr_provcd            AS addr_provcd ,
                p_c_vw.cm_cnsmrid             AS cm_cnsmrid ,
                p_c_vw.email_emailaddr        AS email_emailaddr ,
                p_c_vw.email_emailkey         AS email_emailkey ,
                p_c_vw.fax_telecomkey         AS fax_telecomkey ,
                p_c_vw.fax_telecomnum         AS fax_telecomnum ,
                p_c_vw.phone_telecomkey       AS phone_telecomkey ,
                p_c_vw.phone_telecomnum       AS phone_telecomnum ,
                p_c_vw.altern_telecomkey      AS altern_telecomkey,  
                p_c_vw.altern_telecomnum      AS altern_telecomnum,
                p_c_vw.ptnt_ptntkey           AS ptnt_ptntkey,

                ptntid.idnum                  AS ptntid_idnum ,
                ptntid.idtypkey               AS ptntid_idtypkey ,
                ptntid.issngathrtynm          AS ptntid_issngathrtynm ,
                ptntid.ptntidkey              AS ptntid_ptntidkey ,
                ptntid.ptntkey                AS ptntid_ptntkey ,

                ic.actflg                     AS ic_actflg ,
                ic.bnftcardhldrrltnshptypkey  AS ic_bnftcardhldrrltnshptypkey ,
                ic.cardid                     AS ic_cardid ,
                ic.clntid                     AS ic_clntid ,
                ic.crrid                      AS ic_crrid ,
                ic.grpid                      AS ic_grpid ,
                ic.inscvrgid                  AS ic_inscvrgid ,
                ic.plannum                    AS ic_plannum ,
                ic.ptntcvrgid                 AS ic_ptntcvrgid ,
                ic.ptntcvrgkey                AS ic_ptntcvrgkey ,
                ic.ptntkey                    AS ic_ptntkey ,
                ic.tpid                       AS ic_tpid,
               ic.priority						AS ic_priority,	

                ptntcnsnt.cnsmrid             AS ptntcnsnt_cnsmrid ,
                ptntcnsnt.cnsntefftimestamp   AS ptntcnsnt_cnsntefftimestamp ,
                ptntcnsnt.cnsntendtimestamp   AS ptntcnsnt_cnsntendtimestamp ,
                ptntcnsnt.cnsntovrdrsntypkey  AS ptntcnsnt_cnsntovrdrsntypkey ,
                ptntcnsnt.prdcrid             AS ptntcnsnt_prdcrid ,
                ptntcnsnt.ptntcnsntkey        AS ptntcnsnt_ptntcnsntkey ,
             -- ptntcnsnt.ptntid              AS ptntcnsnt_ptntid ,
                ptntcnsnt.ptntkey             AS ptntcnsnt_ptntkey ,
                ptntcnsnt.txr                 AS ptntcnsnt_txr,
                ptntcnsnt.consenttype         AS ptntcnsnt_consenttype,
                ptntcnsnt.cnsntrsntypkey      AS ptntcnsnt_cnsntrsntypkey,
                ptntcnsnt.consentprovidertype AS ptntcnsnt_consentprovidertype,
                ptntcnsnt.agentfrstnm         AS ptntcnsnt_agentfrstnm,
                ptntcnsnt.agentlstnm          AS ptntcnsnt_agentlstnm,
                ptntcnsnt.agentrelationship	  AS ptntcnsnt_agentrelationship,
                ptntcnsnt.cnsntcrttimestamp AS   ptntcnsnt_cnsntcrttimestamp,
                ptntcnsnt.cnsntupttimestamp AS ptntcnsnt_cnsntupttimestamp,
                ptntcnsnt.userid             AS  ptntcnsnt_userid,
                ptntcnsnt.notifmethod       AS ptntcnsnt_notifmethod,
                null                          AS prl_vw_prov_cddescr ,
                null                          AS prl_vw_prov_cddescrfr ,
                null                          AS prl_vw_prov_cdeffenddt ,
                null                          AS prl_vw_prov_cdeffstrtdt ,
                null                          AS prl_vw_prov_provcd ,
                null                          AS prl_vw_prov_provkey ,
                null                          AS prl_vw_prov_rowid ,
                null                          AS prl_vw_prov_shortcd ,
                null                          AS prl_vw_prscbrtyp_cddescr ,
                null                          AS prl_vw_prscbrtyp_cddescrfr ,
                null                          AS prl_vw_prscbrtyp_cdeffenddt ,
                null                          AS prl_vw_prscbrtyp_cdeffstrtdt ,
                null                          AS prl_vw_prscbrtyp_prscbrtypcd ,
                null                          AS prl_vw_prscbrtyp_prscbrtypkey ,
                null                          AS prl_vw_prscbrtyp_rowid ,
                null                          AS prl_vw_prscbrtyp_shortcd ,
                null                          AS prl_vw_prsnrltyp_cddescr ,
                null                          AS prl_vw_prsnrltyp_cddescrfr ,
                null                          AS prl_vw_prsnrltyp_cdeffenddt ,
                null                          AS prl_vw_prsnrltyp_cdeffstrtdt ,
                null                          AS prl_vw_prsnrltyp_prsnrltypcd ,
                null                          AS prl_vw_prsnrltyp_prsnrltypkey ,
                null                          AS prl_vw_prsnrltyp_rowid ,
                null                          AS prl_vw_prsnrltyp_shortcd ,
                null                          AS prl_vw_prsnrl_isactflg ,
                null                          AS prl_vw_prsnrl_provkey ,
                null                          AS prl_vw_prsnrl_prscbrtypkey ,
                null                          AS prl_vw_prsnrl_prsnkey ,
                null                          AS prl_vw_prsnrl_prsnrlkey ,
                null                          AS prl_vw_prsnrl_prsnrltypkey ,
                null                          AS prl_vw_prsnrl_rowid ,
                null                          AS prl_vw_prsnrl_usrnm ,
                null                          AS prl_vw_prsn_cnsmrid ,
                null                          AS prl_vw_prsn_frstnm ,
                null                          AS prl_vw_prsn_lstnm ,
                null                          AS prl_vw_prsn_mdlnm ,
                null                          AS prl_vw_prsn_mrgdcnsmrid ,
                null                          AS prl_vw_prsn_mrgdtimestamp ,
                null                          AS prl_vw_prsn_prdcrid ,
                null                          AS prl_vw_prsn_prsnid ,
                null                          AS prl_vw_prsn_prsnkey ,
                null                          AS prl_vw_prsn_rowid ,
                null                          AS prl_vw_prsn_storenum ,

                null                          AS cd_c_vw_actvflg ,
                null                          AS cd_c_vw_addr_addrkey ,
                null                          AS cd_c_vw_addr_addrlnone ,
                null                          AS cd_c_vw_addr_addrlntwo ,
                null                          AS cd_c_vw_addr_citynm ,
                null                          AS cd_c_vw_addr_cntrycd ,
                null                          AS cd_c_vw_addr_postalcd ,
                null                          AS cd_c_vw_addr_provcd ,
                null                          AS cd_c_vw_addr_rowid ,
                null                          AS cd_c_vw_addr_type ,
                null                          AS cd_c_vw_addr_type_code ,
                null                          AS cd_c_vw_altern_cntrycd ,
                null                          AS cd_c_vw_altern_rowid ,
                null                          AS cd_c_vw_altern_telecomkey ,
                null                          AS cd_c_vw_altern_telecomnum ,
                null                          AS cd_c_vw_altern_telfaxind ,
                null                          AS cd_c_vw_cm_cnsmrid ,
                null                          AS cd_c_vw_cntctmthdtypcd ,
                null                          AS cd_c_vw_email_emailaddr ,
                null                          AS cd_c_vw_email_emailkey ,
                null                          AS cd_c_vw_email_rowid ,
                null                          AS cd_c_vw_fax_cntrycd ,
                null                          AS cd_c_vw_fax_rowid ,
                null                          AS cd_c_vw_fax_telecomkey ,
                null                          AS cd_c_vw_fax_telecomnum ,
                null                          AS cd_c_vw_fax_telfaxind ,
                null                          AS cd_c_vw_mailflg ,
                null                          AS cd_c_vw_phone_cntrycd ,
                null                          AS cd_c_vw_phone_rowid ,
                null                          AS cd_c_vw_phone_telecomkey ,
                null                          AS cd_c_vw_phone_telecomnum ,
                null                          AS cd_c_vw_phone_telfaxind ,
                null                          AS cd_c_vw_primaryflg ,
                null                          AS cd_c_vw_prsn_prsnkey ,
                null                          AS cd_c_vw_reauthemailflag ,
                null                          AS cd_c_vw_reauthfaxflag ,
                null                          AS cd_c_vw_reauthphoneflag ,
                null                          AS cd_c_vw_reauthvisitflag 
                

           

FROM ptnt ptnt
     LEFT OUTER JOIN ptntid ptntid ON ptnt.ptntkey = ptntid.ptntkey
     LEFT OUTER JOIN (select COALESCE(a.addrkey, -3)  addr_addrkey,
                             a.ADDRLNONE              ADDR_ADDRLNONE,
                             a.ADDRLNTWO              ADDR_ADDRLNTWO,
                             a.CITYNM                 ADDR_CITYNM,
                             a.CNTRYCD                ADDR_CNTRYCD,
                             a.POSTALCD               ADDR_POSTALCD,
                             a.PROVCD                 ADDR_PROVCD,
                             c.CNSMRID                CM_CNSMRID,

                             e.EMAILADDR              EMAIL_EMAILADDR,
                             COALESCE(e.EMAILKEY, -3) EMAIL_EMAILKEY,

                             decode(t.TELFAXIND, 'F', t.TELECOMKEY, -3)   FAX_TELECOMKEY,
                             decode(t.TELFAXIND, 'F', t.TELECOMNUM, null) FAX_TELECOMNUM,

                             decode(t.TELFAXIND, 
                             'T', t.TELECOMKEY,
                             'P', t.TELECOMKEY, -3)                PHONE_TELECOMKEY,
                             decode(t.TELFAXIND, 
                             'T', t.TELECOMNUM,
                             'P', t.TELECOMNUM, null)              PHONE_TELECOMNUM,
                              decode(t.TELFAXIND, 'A', t.TELECOMKEY, -3)   ALTERN_TELECOMKEY,
                             decode(t.TELFAXIND, 'A', t.TELECOMNUM, null) ALTERN_TELECOMNUM,

                             c.ptntkey ptnt_ptntkey

                        from cntctmthd  c
                                left outer join addr a
                                  on c.cntctmthdtypcd = 'Postal Address' and
                                     c.cntctmthdkey   = a.addrkey
                              
                                left outer join telecom  t
                                  on c.cntctmthdtypcd = 'Telecom' and
                                     c.cntctmthdkey   = t.telecomkey

                                left outer join email    e
                                  on c.cntctmthdtypcd = 'Email Address' and
                                     c.cntctmthdkey   = e.emailkey
                       where c.ptntkey = ?) p_c_vw
                 ON ptnt.ptntkey = p_c_vw.ptnt_ptntkey

      LEFT OUTER JOIN ptntcvrg  ic        ON ptnt.ptntkey = ic.ptntkey
      LEFT OUTER JOIN ptntcnsnt ptntcnsnt ON ptnt.ptntkey = ptntcnsnt.ptntkey

where   	ptnt.ptntKey = ?  	
order by   	Ptnt.PtntKey,   
            ptntid.ptntidkey desc,
			IC.PtntCvrgKey,
		    PtntCnsnt.PtntCnsntKey