
package ca.shoppersdrugmart.rxhb.drx.medicationprofileservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetDispense;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetDispenseAdherenceCalendar;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetDispenseAdherenceCalendarResponse;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetDispenseResponse;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPatientAdherenceCalendar;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPatientAdherenceCalendarResponse;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPrescription;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPrescriptionAdherenceCalendar;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPrescriptionAdherenceCalendarResponse;
import ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPrescriptionResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MedicationProfile", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfileService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ca.shoppersdrugmart.rxhb.drx.cse.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.drx.medicationprofile.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class
})
public interface MedicationProfile {


    /**
     * 
     * @param getPrescription
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPrescriptionResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/MedicationProfile/getPrescription")
    @WebResult(name = "GetPrescriptionResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetPrescriptionResponse")
    public GetPrescriptionResponse getPrescription(
        @WebParam(name = "GetPrescription", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetPrescription")
        GetPrescription getPrescription);

    /**
     * 
     * @param getDispense
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetDispenseResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/MedicationProfile/getDispense")
    @WebResult(name = "GetDispenseResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetDispenseResponse")
    public GetDispenseResponse getDispense(
        @WebParam(name = "GetDispense", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetDispense")
        GetDispense getDispense);

    /**
     * 
     * @param getPrescriptionAdherenceCalendar
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPrescriptionAdherenceCalendarResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/MedicationProfile/getPrescriptionAdherenceCalendar")
    @WebResult(name = "GetPrescriptionAdherenceCalendarResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetPrescriptionAdherenceCalendarResponse")
    public GetPrescriptionAdherenceCalendarResponse getPrescriptionAdherenceCalendar(
        @WebParam(name = "GetPrescriptionAdherenceCalendar", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetPrescriptionAdherenceCalendar")
        GetPrescriptionAdherenceCalendar getPrescriptionAdherenceCalendar);

    /**
     * 
     * @param getDispenseAdherenceCalendar
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetDispenseAdherenceCalendarResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/MedicationProfile/getDispenseAdherenceCalendar")
    @WebResult(name = "GetDispenseAdherenceCalendarResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetDispenseAdherenceCalendarResponse")
    public GetDispenseAdherenceCalendarResponse getDispenseAdherenceCalendar(
        @WebParam(name = "GetDispenseAdherenceCalendar", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetDispenseAdherenceCalendar")
        GetDispenseAdherenceCalendar getDispenseAdherenceCalendar);

    /**
     * 
     * @param getPatientAdherenceCalendar
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.medicationprofile.GetPatientAdherenceCalendarResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/MedicationProfile/getPatientAdherenceCalendar")
    @WebResult(name = "GetPatientAdherenceCalendarResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetPatientAdherenceCalendarResponse")
    public GetPatientAdherenceCalendarResponse getPatientAdherenceCalendar(
        @WebParam(name = "GetPatientAdherenceCalendar", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationProfile", partName = "GetPatientAdherenceCalendar")
        GetPatientAdherenceCalendar getPatientAdherenceCalendar);

}
