
package ca.shoppersdrugmart.cdr.notificationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;




/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NotificationService", targetNamespace = "http://shoppersdrugmart.ca/cdr/notificationService/NotificationService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ca.shoppersdrugmart.rxhb.drx.subscriptionservice.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class
})
public interface NotificationService {


	/**
     * 
     * @param notificationProcess to Drug
     * @return
     */
	@WebMethod(action = "http://shoppersdrugmart.ca/cdr/notificationService/notificationProcess")
    @WebResult(name = "NotificationResponse", targetNamespace = "http://shoppersdrugmart.ca/cdr/notificationService/NotificationService", partName = "NotificationResponse")
    
	public NotificationResponse notificationProcess(
	@WebParam(name = "NotificationRequest", targetNamespace = "http://shoppersdrugmart.ca/cdr/notificationService/NotificationService", partName = "NotificationRequest")
	NotificationRequest notificationRequest);
	
   
}
