
package ca.shoppersdrugmart.rxhb.drx.medicationreviewservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MedicationReviewService", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationReviewService", wsdlLocation = "/wsdls/MedicationReview.wsdl")
public class MedicationReviewService
    extends Service
{

    private final static URL MEDICATIONREVIEWSERVICE_WSDL_LOCATION;
    private final static WebServiceException MEDICATIONREVIEWSERVICE_EXCEPTION;
    private final static QName MEDICATIONREVIEWSERVICE_QNAME = new QName("http://shoppersdrugmart.ca/RxHB/DRx/MedicationReviewService", "MedicationReviewService");

    static {
        MEDICATIONREVIEWSERVICE_WSDL_LOCATION = ca.shoppersdrugmart.rxhb.drx.medicationreviewservice.MedicationReviewService.class.getResource("/wsdls/MedicationReview.wsdl");
        WebServiceException e = null;
        if (MEDICATIONREVIEWSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/MedicationReview.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        MEDICATIONREVIEWSERVICE_EXCEPTION = e;
    }

    public MedicationReviewService() {
        super(__getWsdlLocation(), MEDICATIONREVIEWSERVICE_QNAME);
    }

    public MedicationReviewService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MEDICATIONREVIEWSERVICE_QNAME, features);
    }

    public MedicationReviewService(URL wsdlLocation) {
        super(wsdlLocation, MEDICATIONREVIEWSERVICE_QNAME);
    }

    public MedicationReviewService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MEDICATIONREVIEWSERVICE_QNAME, features);
    }

    public MedicationReviewService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MedicationReviewService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MedicationReview
     */
    @WebEndpoint(name = "MedicationReview")
    public MedicationReview getMedicationReview() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/MedicationReviewService", "MedicationReview"), MedicationReview.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MedicationReview
     */
    @WebEndpoint(name = "MedicationReview")
    public MedicationReview getMedicationReview(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/MedicationReviewService", "MedicationReview"), MedicationReview.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MEDICATIONREVIEWSERVICE_EXCEPTION!= null) {
            throw MEDICATIONREVIEWSERVICE_EXCEPTION;
        }
        return MEDICATIONREVIEWSERVICE_WSDL_LOCATION;
    }

}
