
package ca.shoppersdrugmart.rxhb.drx.medicationreviewservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ca.shoppersdrugmart.rxhb.drx.medicationreview.GetMedicationReviewRequest;
import ca.shoppersdrugmart.rxhb.drx.medicationreview.GetMedicationReviewResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MedicationReview", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationReviewService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ca.shoppersdrugmart.rxhb.drx.medicationreview.ObjectFactory.class,
    com.ibm.rules.decisionservice.medcheckruleapp.medcheckdetermination.ObjectFactory.class
})
public interface MedicationReview {


    /**
     * 
     * @param getMedicationReviewRequest
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.medicationreview.GetMedicationReviewResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/MedicationReview/getMedicationReview")
    @WebResult(name = "GetMedicationReviewResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationReview", partName = "GetMedicationReviewResponse")
    public GetMedicationReviewResponse getMedicationReview(
        @WebParam(name = "GetMedicationReviewRequest", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationReview", partName = "GetMedicationReviewRequest")
        GetMedicationReviewRequest getMedicationReviewRequest);

}
