//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 03:59:05 PM EST 
//


package ca.shoppersdrugmart.rxhb.ehealth.sourcepharmacychannel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sourcePharmacyChannel" type="{http://shoppersdrugmart.ca/RxHB/eHealth/SourcePharmacyChannel}SourcePharmacyChannelMap" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourcePharmacyChannel"
})
@XmlRootElement(name = "SourcePharmacyChannel")
public class SourcePharmacyChannel {

    @XmlElement(required = true)
    protected List<SourcePharmacyChannelMap> sourcePharmacyChannel;

    /**
     * Gets the value of the sourcePharmacyChannel property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sourcePharmacyChannel property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSourcePharmacyChannel().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SourcePharmacyChannelMap }
     * 
     * 
     */
    public List<SourcePharmacyChannelMap> getSourcePharmacyChannel() {
        if (sourcePharmacyChannel == null) {
            sourcePharmacyChannel = new ArrayList<SourcePharmacyChannelMap>();
        }
        return this.sourcePharmacyChannel;
    }

}
