//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 03:59:05 PM EST 
//


package ca.shoppersdrugmart.rxhb.ehealth.sourcepharmacychannel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import ca.shoppersdrugmart.rxhb.ehealth.PharmacyChannel;
import ca.shoppersdrugmart.rxhb.ehealth.TransactionSourceChannel;


/**
 * <p>Java class for SourcePharmacyChannelMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourcePharmacyChannelMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transactionSourceChannel" type="{http://shoppersdrugmart.ca/RxHB/eHealth}TransactionSourceChannel"/>
 *         &lt;element name="pharmacyChannel" type="{http://shoppersdrugmart.ca/RxHB/eHealth}PharmacyChannel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourcePharmacyChannelMap", propOrder = {
    "transactionSourceChannel",
    "pharmacyChannel"
})
public class SourcePharmacyChannelMap {

    @XmlElement(required = true)
    protected TransactionSourceChannel transactionSourceChannel;
    @XmlElement(required = true)
    protected PharmacyChannel pharmacyChannel;

    /**
     * Gets the value of the transactionSourceChannel property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionSourceChannel }
     *     
     */
    public TransactionSourceChannel getTransactionSourceChannel() {
        return transactionSourceChannel;
    }

    /**
     * Sets the value of the transactionSourceChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionSourceChannel }
     *     
     */
    public void setTransactionSourceChannel(TransactionSourceChannel value) {
        this.transactionSourceChannel = value;
    }

    /**
     * Gets the value of the pharmacyChannel property.
     * 
     * @return
     *     possible object is
     *     {@link PharmacyChannel }
     *     
     */
    public PharmacyChannel getPharmacyChannel() {
        return pharmacyChannel;
    }

    /**
     * Sets the value of the pharmacyChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link PharmacyChannel }
     *     
     */
    public void setPharmacyChannel(PharmacyChannel value) {
        this.pharmacyChannel = value;
    }

}
