
package ca.shoppersdrugmart.cdr.prescriberupsertservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrescriberUpsertService", targetNamespace = "http://shoppersdrugmart.ca/cdr/PrescriberUpsertService", wsdlLocation = "/wsdls/UpsertPrescriber.wsdl")
public class PrescriberUpsertService_Service
    extends Service
{

    private final static URL PRESCRIBERUPSERTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRESCRIBERUPSERTSERVICE_EXCEPTION;
    private final static QName PRESCRIBERUPSERTSERVICE_QNAME = new QName("http://shoppersdrugmart.ca/cdr/PrescriberUpsertService", "PrescriberUpsertService");

    static {
        PRESCRIBERUPSERTSERVICE_WSDL_LOCATION = ca.shoppersdrugmart.cdr.prescriberupsertservice.PrescriberUpsertService_Service.class.getResource("/wsdls/UpsertPrescriber.wsdl");
        WebServiceException e = null;
        if (PRESCRIBERUPSERTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/UpsertPrescriber.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PRESCRIBERUPSERTSERVICE_EXCEPTION = e;
    }

    public PrescriberUpsertService_Service() {
        super(__getWsdlLocation(), PRESCRIBERUPSERTSERVICE_QNAME);
    }

    public PrescriberUpsertService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRESCRIBERUPSERTSERVICE_QNAME, features);
    }

    public PrescriberUpsertService_Service(URL wsdlLocation) {
        super(wsdlLocation, PRESCRIBERUPSERTSERVICE_QNAME);
    }

    public PrescriberUpsertService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRESCRIBERUPSERTSERVICE_QNAME, features);
    }

    public PrescriberUpsertService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrescriberUpsertService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrescriberUpsertService
     */
    @WebEndpoint(name = "PrescriberUpsertService")
    public PrescriberUpsertService getPrescriberUpsertService() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PrescriberUpsertService", "PrescriberUpsertService"), PrescriberUpsertService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrescriberUpsertService
     */
    @WebEndpoint(name = "PrescriberUpsertService")
    public PrescriberUpsertService getPrescriberUpsertService(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PrescriberUpsertService", "PrescriberUpsertService"), PrescriberUpsertService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRESCRIBERUPSERTSERVICE_EXCEPTION!= null) {
            throw PRESCRIBERUPSERTSERVICE_EXCEPTION;
        }
        return PRESCRIBERUPSERTSERVICE_WSDL_LOCATION;
    }

}
