
package ca.shoppersdrugmart.rxhb.drx.subscriptionserviceservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.SubscribeToPatient;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.SubscribeToPatientResponse;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.SubscribeToRx;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.SubscribeToRxResponse;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.UnsubscribeToPatient;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.UnsubscribeToPatientResponse;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.UnsubscribeToRx;
import ca.shoppersdrugmart.rxhb.drx.subscriptionservice.UnsubscribeToRxResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SubscriptionService", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceServices")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ca.shoppersdrugmart.rxhb.drx.subscriptionservice.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class
})
public interface SubscriptionService {


    /**
     * 
     * @param subscribeToPatient
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.subscriptionservice.SubscribeToPatientResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/SubscriptionService/subscribeToPatient")
    @WebResult(name = "SubscribeToPatientResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "SubscribeToPatientResponse")
    public SubscribeToPatientResponse subscribeToPatient(
        @WebParam(name = "SubscribeToPatient", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "SubscribeToPatient")
        SubscribeToPatient subscribeToPatient);

    /**
     * 
     * @param subscribeToRx
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.subscriptionservice.SubscribeToRxResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/SubscriptionService/subscribeToRx")
    @WebResult(name = "SubscribeToRxResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "SubscribeToRxResponse")
    public SubscribeToRxResponse subscribeToRx(
        @WebParam(name = "SubscribeToRx", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "SubscribeToRx")
        SubscribeToRx subscribeToRx);

    /**
     * 
     * @param unsubscribeToPatient
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.subscriptionservice.UnsubscribeToPatientResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/SubscriptionService/unsubscribeToPatient")
    @WebResult(name = "UnsubscribeToPatientResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "UnsubscribeToPatientResponse")
    public UnsubscribeToPatientResponse unSubscribeToPatient(
        @WebParam(name = "UnsubscribeToPatient", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "UnsubscribeToPatient")
        UnsubscribeToPatient unsubscribeToPatient);

    /**
     * 
     * @param unsubscribeToRx
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.subscriptionservice.UnsubscribeToRxResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/SubscriptionService/unsubscribeToRx")
    @WebResult(name = "UnsubscribeToRxResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "UnsubscribeToRxResponse")
    public UnsubscribeToRxResponse unSubscribeToRx(
        @WebParam(name = "UnsubscribeToRx", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionService", partName = "UnsubscribeToRx")
        UnsubscribeToRx unsubscribeToRx);

}
