
package ca.shoppersdrugmart.rxhb.drx.subscriptionserviceservices;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SubscriptionService", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceServices", wsdlLocation = "/wsdls/SubscriptionService.wsdl")
public class SubscriptionService_Service
    extends Service
{

    private final static URL SUBSCRIPTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUBSCRIPTIONSERVICE_EXCEPTION;
    private final static QName SUBSCRIPTIONSERVICE_QNAME = new QName("http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceServices", "SubscriptionService");

    static {
        SUBSCRIPTIONSERVICE_WSDL_LOCATION = ca.shoppersdrugmart.rxhb.drx.subscriptionserviceservices.SubscriptionService_Service.class.getResource("/wsdls/SubscriptionService.wsdl");
        WebServiceException e = null;
        if (SUBSCRIPTIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/SubscriptionService.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        SUBSCRIPTIONSERVICE_EXCEPTION = e;
    }

    public SubscriptionService_Service() {
        super(__getWsdlLocation(), SUBSCRIPTIONSERVICE_QNAME);
    }

    public SubscriptionService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUBSCRIPTIONSERVICE_QNAME, features);
    }

    public SubscriptionService_Service(URL wsdlLocation) {
        super(wsdlLocation, SUBSCRIPTIONSERVICE_QNAME);
    }

    public SubscriptionService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUBSCRIPTIONSERVICE_QNAME, features);
    }

    public SubscriptionService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SubscriptionService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SubscriptionService
     */
    @WebEndpoint(name = "SubscriptoinService")
    public SubscriptionService getSubscriptoinService() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceServices", "SubscriptoinService"), SubscriptionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SubscriptionService
     */
    @WebEndpoint(name = "SubscriptoinService")
    public SubscriptionService getSubscriptoinService(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/RxHB/DRx/SubscriptionServiceServices", "SubscriptoinService"), SubscriptionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUBSCRIPTIONSERVICE_EXCEPTION!= null) {
            throw SUBSCRIPTIONSERVICE_EXCEPTION;
        }
        return SUBSCRIPTIONSERVICE_WSDL_LOCATION;
    }

}
