
package ca.shoppersdrugmart.rxhb.drx.patientservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatient;
import ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientByPatientId;
import ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientByPatientIdResponse;
import ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientByQueryCriteria;
import ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientByQueryCriteriaResponse;
import ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PatientService", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/PatientService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ca.shoppersdrugmart.rxhb.drx.cse.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.drx.getpatient.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class
})
public interface PatientService {


    /**
     * 
     * @param getPatient
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/getPatientService/getPatient")
    @WebResult(name = "GetPatientResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/GetPatient", partName = "GetPatientResponse")
    public GetPatientResponse getPatient(
        @WebParam(name = "GetPatient", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/GetPatient", partName = "GetPatient")
        GetPatient getPatient);

    /**
     * 
     * @param getPatientByPatientId
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientByPatientIdResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/getPatientService/getPatientByPatientId")
    @WebResult(name = "GetPatientByPatientIdResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/GetPatient", partName = "GetPatientByPatientIdResponse")
    public GetPatientByPatientIdResponse getPatientByPatientId(
        @WebParam(name = "GetPatientByPatientId", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/GetPatient", partName = "GetPatientByPatientId")
        GetPatientByPatientId getPatientByPatientId);

    /**
     * 
     * @param getPatientByQueryCriteria
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.getpatient.GetPatientByQueryCriteriaResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/getPatientService/getPatientByQueryCriteria")
    @WebResult(name = "GetPatientByQueryCriteriaResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/GetPatient", partName = "GetPatientByQueryCriteriaResponse")
    public GetPatientByQueryCriteriaResponse getPatientByQueryCriteria(
        @WebParam(name = "GetPatientByQueryCriteria", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/GetPatient", partName = "GetPatientByQueryCriteria")
        GetPatientByQueryCriteria getPatientByQueryCriteria);

}
