
package ca.shoppersdrugmart.cdr.patientupsertservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ca.shoppersdrugmart.cdr.cdrcommoneventpersist.PatientUpsert;
import ca.shoppersdrugmart.cdr.cdrcommoneventpersist.PatientUpsertResponse;


/**
 * Put attributes and operations
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PatientUpsertService", targetNamespace = "http://shoppersdrugmart.ca/cdr/PatientUpsertService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ca.shoppersdrugmart.cdr.cdrcommoneventpersist.ObjectFactory.class,
    ca.shoppersdrugmart.cdr.patientupsertservice.ObjectFactory.class,
    ca.shoppersdrugmart.message.errorxml.ObjectFactory.class,
    ca.shoppersdrugmart.rx.trr.businesseventmessagetype.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.businessevent.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.pharmacycentralevent.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface PatientUpsertService {


    /**
     * 
     * @param patientUpsert
     * @return
     *     returns ca.shoppersdrugmart.cdr.cdrcommoneventpersist.PatientUpsertResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/cdr/PatientUpsertService/PatientUpsert")
    @WebResult(name = "PatientUpsertResponse", targetNamespace = "http://shoppersdrugmart.ca/cdr/CDRCommonEventPersist", partName = "PatientUpsertResponse")
    public PatientUpsertResponse patientUpsert(
        @WebParam(name = "PatientUpsert", targetNamespace = "http://shoppersdrugmart.ca/cdr/CDRCommonEventPersist", partName = "PatientUpsert")
        PatientUpsert patientUpsert);

}
