
package ca.shoppersdrugmart.cdr.patientupsertservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PatientUpsertService", targetNamespace = "http://shoppersdrugmart.ca/cdr/PatientUpsertService", wsdlLocation = "/wsdls/UpsertPatient.wsdl")
public class PatientUpsertService_Service
    extends Service
{

    private final static URL PATIENTUPSERTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PATIENTUPSERTSERVICE_EXCEPTION;
    private final static QName PATIENTUPSERTSERVICE_QNAME = new QName("http://shoppersdrugmart.ca/cdr/PatientUpsertService", "PatientUpsertService");

    static {
        PATIENTUPSERTSERVICE_WSDL_LOCATION = ca.shoppersdrugmart.cdr.patientupsertservice.PatientUpsertService_Service.class.getResource("/wsdls/UpsertPatient.wsdl");
        WebServiceException e = null;
        if (PATIENTUPSERTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/UpsertPatient.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PATIENTUPSERTSERVICE_EXCEPTION = e;
    }

    public PatientUpsertService_Service() {
        super(__getWsdlLocation(), PATIENTUPSERTSERVICE_QNAME);
    }

    public PatientUpsertService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PATIENTUPSERTSERVICE_QNAME, features);
    }

    public PatientUpsertService_Service(URL wsdlLocation) {
        super(wsdlLocation, PATIENTUPSERTSERVICE_QNAME);
    }

    public PatientUpsertService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PATIENTUPSERTSERVICE_QNAME, features);
    }

    public PatientUpsertService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PatientUpsertService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PatientUpsertService
     */
    @WebEndpoint(name = "PatientUpsertService")
    public PatientUpsertService getPatientUpsertService() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PatientUpsertService", "PatientUpsertService"), PatientUpsertService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PatientUpsertService
     */
    @WebEndpoint(name = "PatientUpsertService")
    public PatientUpsertService getPatientUpsertService(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PatientUpsertService", "PatientUpsertService"), PatientUpsertService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PATIENTUPSERTSERVICE_EXCEPTION!= null) {
            throw PATIENTUPSERTSERVICE_EXCEPTION;
        }
        return PATIENTUPSERTSERVICE_WSDL_LOCATION;
    }

}
