
package ca.shoppersdrugmart.rxhb.drx.medicationrefilleligibilityservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import ca.shoppersdrugmart.rxhb.drx.medicationrefilleligibility.GetPatientAdherenceEligibility;
import ca.shoppersdrugmart.rxhb.drx.medicationrefilleligibility.GetPatientAdherenceEligibilityResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MedicationRefillEligibility", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationRefillEligibilityService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ca.shoppersdrugmart.message.errorxml.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.drx.cse.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.drx.medicationrefilleligibility.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class
})
public interface MedicationRefillEligibility {


    /**
     * 
     * @param getPatientAdherenceEligibility
     * @return
     *     returns ca.shoppersdrugmart.rxhb.drx.medicationrefilleligibility.GetPatientAdherenceEligibilityResponse
     */
    @WebMethod(action = "http://shoppersdrugmart.ca/RxHB/DigitalRx/MedicationProfile/getPatientAdherenceCalendar")
    @WebResult(name = "GetPatientAdherenceEligibilityResponse", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationRefillEligibility", partName = "GetPatientAdherenceEligibilityResponse")
    public GetPatientAdherenceEligibilityResponse getPatientAdherenceEligibility(
        @WebParam(name = "GetPatientAdherenceEligibility", targetNamespace = "http://shoppersdrugmart.ca/RxHB/DRx/MedicationRefillEligibility", partName = "GetPatientAdherenceEligibility")
        GetPatientAdherenceEligibility getPatientAdherenceEligibility);

}
