
package ca.shoppersdrugmart.cdr.prescriptionupsertservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ca.shoppersdrugmart.cdr.cdrcommoneventpersist.CDRPersistResponse;
import ca.shoppersdrugmart.rxhb.pharmacycentralevent.PharmacyCentralBusinessEvent;


/**
 * Put attributes and operations
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PrescriptionUpsertService", targetNamespace = "http://shoppersdrugmart.ca/cdr/PrescriptionUpsertService")
@XmlSeeAlso({
    ca.shoppersdrugmart.cdr.cdrcommoneventpersist.ObjectFactory.class,
    ca.shoppersdrugmart.cdr.prescriptionupsertservice.ObjectFactory.class,
    ca.shoppersdrugmart.message.errorxml.ObjectFactory.class,
    ca.shoppersdrugmart.rx.trr.businesseventmessagetype.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.ehealth.businessevent.ObjectFactory.class,
    ca.shoppersdrugmart.rxhb.pharmacycentralevent.ObjectFactory.class,
    generated.ObjectFactory.class
})
public interface PrescriptionUpsertService {


    /**
     * 
     * @param pharmacyBusinessEvent
     * @return
     *     returns ca.shoppersdrugmart.cdr.cdrcommoneventpersist.CDRPersistResponse
     */
    @WebMethod(operationName = "PrescriptionUpsert", action = "http://shoppersdrugmart.ca/cdr/PrescriptionUpsertService/PrescriptionUpsert")
    @WebResult(name = "response", targetNamespace = "http://shoppersdrugmart.ca/cdr/CDRCommonEventPersist")
    @RequestWrapper(localName = "PrescriptionUpsert", targetNamespace = "http://shoppersdrugmart.ca/cdr/CDRCommonEventPersist", className = "ca.shoppersdrugmart.cdr.cdrcommoneventpersist.PrescriptionUpsert")
    @ResponseWrapper(localName = "PrescriptionUpsertResponse", targetNamespace = "http://shoppersdrugmart.ca/cdr/CDRCommonEventPersist", className = "ca.shoppersdrugmart.cdr.cdrcommoneventpersist.PrescriptionUpsertResponse")
    public CDRPersistResponse prescriptionUpsert(
        @WebParam(name = "pharmacyBusinessEvent", targetNamespace = "http://shoppersdrugmart.ca/cdr/CDRCommonEventPersist")
        PharmacyCentralBusinessEvent pharmacyBusinessEvent);

}
