
package ca.shoppersdrugmart.cdr.prescriptionupsertservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8-b13937
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrescriptionUpsertService", targetNamespace = "http://shoppersdrugmart.ca/cdr/PrescriptionUpsertService", wsdlLocation = "/wsdls/UpsertPrescription.wsdl")
public class PrescriptionUpsertService_Service
    extends Service
{

    private final static URL PRESCRIPTIONUPSERTSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRESCRIPTIONUPSERTSERVICE_EXCEPTION;
    private final static QName PRESCRIPTIONUPSERTSERVICE_QNAME = new QName("http://shoppersdrugmart.ca/cdr/PrescriptionUpsertService", "PrescriptionUpsertService");

    static {
        PRESCRIPTIONUPSERTSERVICE_WSDL_LOCATION = ca.shoppersdrugmart.cdr.prescriptionupsertservice.PrescriptionUpsertService_Service.class.getResource("/wsdls/UpsertPrescription.wsdl");
        WebServiceException e = null;
        if (PRESCRIPTIONUPSERTSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdls/UpsertPrescription.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PRESCRIPTIONUPSERTSERVICE_EXCEPTION = e;
    }

    public PrescriptionUpsertService_Service() {
        super(__getWsdlLocation(), PRESCRIPTIONUPSERTSERVICE_QNAME);
    }

    public PrescriptionUpsertService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRESCRIPTIONUPSERTSERVICE_QNAME, features);
    }

    public PrescriptionUpsertService_Service(URL wsdlLocation) {
        super(wsdlLocation, PRESCRIPTIONUPSERTSERVICE_QNAME);
    }

    public PrescriptionUpsertService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRESCRIPTIONUPSERTSERVICE_QNAME, features);
    }

    public PrescriptionUpsertService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrescriptionUpsertService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrescriptionUpsertService
     */
    @WebEndpoint(name = "PrescriptionUpsertService")
    public PrescriptionUpsertService getPrescriptionUpsertService() {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PrescriptionUpsertService", "PrescriptionUpsertService"), PrescriptionUpsertService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrescriptionUpsertService
     */
    @WebEndpoint(name = "PrescriptionUpsertService")
    public PrescriptionUpsertService getPrescriptionUpsertService(WebServiceFeature... features) {
        return super.getPort(new QName("http://shoppersdrugmart.ca/cdr/PrescriptionUpsertService", "PrescriptionUpsertService"), PrescriptionUpsertService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRESCRIPTIONUPSERTSERVICE_EXCEPTION!= null) {
            throw PRESCRIPTIONUPSERTSERVICE_EXCEPTION;
        }
        return PRESCRIPTIONUPSERTSERVICE_WSDL_LOCATION;
    }

}
